# Generated by Django 5.1.1 on 2024-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-fiction'), ('fantasy', 'Fantasy'), ('science_fiction', 'Science Fiction'), ('mystery', 'Mystery'), ('biography', 'Biography')], max_length=20)),
                ('published_date', models.DateField()),
                ('pages', models.IntegerField()),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
