# Generated by Django 5.1.1 on 2024-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('pages', models.IntegerField(verbose_name='Number of Pages')),
                ('description', models.TextField(verbose_name='Description')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('publisher', models.CharField(max_length=255, verbose_name='Publisher')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
