# Generated by Django 5.1.1 on 2024-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_cover_image_book_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(null=True, verbose_name='white your news'),
        ),
        migrations.AddField(
            model_name='post',
            name='email_news',
            field=models.EmailField(max_length=254, null=True, verbose_name='white  email news company'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post/', verbose_name='download picture'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_or_dislike',
            field=models.CharField(choices=[('👍🏻', '👍🏻'), ('👎🏻', '👎🏻')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='enter title news'),
        ),
        migrations.AddField(
            model_name='post',
            name='url_news',
            field=models.URLField(null=True, verbose_name='white your url news'),
        ),
    ]
