# Generated by Django 5.1.1 on 2024-09-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_delete_book_post_created_at_post_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Cover Image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('like_or_dislike', models.CharField(blank=True, max_length=100, null=True, verbose_name='Like or Dislike')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email_news',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_or_dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url_news',
        ),
    ]
