# Generated by Django 5.1.1 on 2024-09-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_tag_reviewpost_cloth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Book',
        ),
    ]
